#!/bin/bash

#
# This file is part of Proto²Testbed.
#
# Copyright (C) 2024 Martin Ottens
# 
# This program is free software: you can redistribute it and/or modify 
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, 
# but WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the 
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see https://www.gnu.org/licenses/.
#

# Resolve symlinks by passing $0 to realpath
SCRIPT=$(realpath "$0")
REPO_BASE=$(dirname "$SCRIPT")

CALLER_SCRIPT=$(basename "$0")
export CALLER_SCRIPT

while true; do
    python3 $REPO_BASE/controller/main.py ${@:1}
    exit_code=$?

    if [ $exit_code -ne 254 ]; then
        exit $exit_code
    fi
done
